driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6.5
- name: centos-5.10
- name: fedora-19
- name: fedora-20

suites:
- name: default
  run_list: ["recipe[selinux]"]
  attributes: {}
